/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class com_example_casa_myapplication_NativeClass */

#include <com_example_casa_myapplication_NativeClass.h>
JNIEXPORT jstring JNICALL Java_com_example_casa_myapplication_NativeClass_getMessageFromJNI
  (JNIEnv *env, jclass obj){
    return env->NewStringUTF ("Essa uma mensagem do JNI");
}
